version: '3.8'

services:
  comm-service:
    build:
      context: ./portfolio-services/communication
    ports:
      - "3001:3001"

  react-app:
    build:
      context: ./portfolio-ui
    ports:
      - "3000:3000"
