apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-t1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app-t1
  template:
    metadata:
      labels:
        app: react-app-t1
    spec:
      containers:
      - name: react-app-t1
        image: portfoligo-react-app:latest
        imagePullPolicy: Never  # Ensure local image is used
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: react-app-t1
spec:
  selector:
    app: react-app-t1
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
